import { StyleSheet, Dimensions } from "react-native";

// Pega a largura da tela do dispositivo para os cálculos de posicionamento
const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
  main: {
    backgroundColor: '#9c2222',
    paddingVertical: 105,
    paddingHorizontal: 25,
    display: 'flex',
    flexDirection: 'column',
    gap: 225,
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1, // Faz a View ocupar a tela inteira independente do dispositivo
    position: 'relative',
    overflow: 'hidden',
  },
  elementoEstatico: {
    flexShrink: 0,
    width: 328,
    height: 188,
  },
  suptituloTexto: {
    color: '#ececec',
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular', 
    fontSize: 20,
    lineHeight: 20.65,
    fontWeight: '400',
    position: 'absolute',
    left: screenWidth / 2,
    transform: [{ translateX: -164 }], // Centraliza baseado na largura de 328
    top: 251,
    width: 328,
  },
  logoImagem: {
    width: 327,
    height: 80,
    position: 'absolute',
    left: screenWidth / 2,
    transform: [{ translateX: -163.5 }], // Centraliza baseado na largura de 327
    top: 105,
    resizeMode: 'contain', // Melhor que 'cover' para logos
  },
  elementoAcao: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    flexShrink: 0,
    width: 342.16,
    position: 'relative',
  },
  botaoEntrar: {
    flexShrink: 0,
    width: 342.16,
    height: 94.56,
  },
  formatoBotao: {
    backgroundColor: '#fdfdfd',
    borderRadius: 25,
    borderStyle: 'solid',
    borderColor: '#9c2222',
    borderWidth: 1,
    width: '72.29%',
    height: '36.19%',
    position: 'absolute',
    right: '14.29%',
    left: '13.43%',
    bottom: '59.17%',
    top: '4.64%',
  },
  entrarTexto: {
    color: '#9c2222',
    textAlign: 'center',
    fontFamily: 'Nunito-Bold',
    fontSize: 20,
    lineHeight: 30.57,
    letterSpacing: 0.68,
    fontWeight: '700',
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
    position: 'absolute',
    width: '100%',
    bottom: '55%',
    top: '0%',
    height: '45%',
    textAlignVertical: 'center',
  },
  ouTexto: {
    color: '#ffffff',
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular',
    fontSize: 20,
    lineHeight: 20.65,
    fontWeight: '400',
    alignSelf: 'stretch',
  },
  botaoCadastrar: {
    flexShrink: 0,
    width: 342.16,
    height: 94.56,
  },
  formatoBotao2: {
    backgroundColor: '#fdfdfd',
    borderRadius: 25,
    borderStyle: 'solid',
    borderColor: '#9c2222',
    borderWidth: 1,
    width: '72.29%',
    height: '36.19%',
    position: 'absolute',
    right: '14.29%',
    left: '13.43%',
    bottom: '4.18%',
    top: '59.64%',
  },
  cadastrarTexto: {
    color: '#9c2222',
    textAlign: 'center',
    fontFamily: 'Nunito-Bold',
    fontSize: 20,
    lineHeight: 30.57,
    letterSpacing: 0.68,
    fontWeight: '700',
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
    position: 'absolute',
    width: '100%',
    bottom: '0%',
    top: '55%',
    height: '45%',
    textAlignVertical: 'center',
  }
});

export default styles;
