import { StyleSheet, Dimensions } from "react-native";

// Pega a largura da tela do dispositivo para os cálculos de posicionamento
const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
  main: {
    backgroundColor: '#9c2222',
    paddingVertical: 105,
    paddingHorizontal: 25,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 852,
    position: 'relative',
    overflow: 'hidden',
  },
  conteudo: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'stretch',
    flex: 0,
    height: 643.42,
    position: 'relative',
  },
  elementoEstatico: {
    display: 'flex',
    flexDirection: 'column',
    gap: 73,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flex: 0,
    position: 'relative',
    aspectRatio: 343 / 208.3,
  },
  logoImagem: {
    flex: 0,
    width: 341.95,
    height: 88.72,
    position: 'relative',
    resizeMode: 'cover',
    aspectRatio: 341.95 / 88.72,
  },
  suptituloTexto: {
    color: '#ececec',
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular',
    fontSize: 20,
    lineHeight: 20.65,
    fontWeight: '400',
    position: 'relative',
    width: 343,
    height: 46.58,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  elementoAcao: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    flex: 0,
    position: 'relative',
  },
  botaoEntrar: {
    flex: 0,
    width: 342.16,
    height: 94.56,
    position: 'static',
  },
  formatoBotao: {
    backgroundColor: '#fdfdfd',
    borderRadius: 25,
    borderStyle: 'solid',
    borderColor: '#9c2222',
    borderWidth: 1,
    width: '72.11%',
    height: '36.19%',
    position: 'absolute',
    right: '14.37%',
    left: '13.52%',
    bottom: '59.17%',
    top: '4.64%',
  },
  entrarTexto: {
    color: '#9c2222',
    textAlign: 'center',
    fontFamily: 'Nunito-Bold',
    fontSize: 20,
    lineHeight: 30.57,
    letterSpacing: 0.68,
    fontWeight: '700',
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
    position: 'absolute',
    right: '0.12%',
    left: '0.12%',
    width: '99.76%',
    bottom: '55%',
    top: '0%',
    height: '45%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ouTexto: {
    color: '#ffffff',
    textAlign: 'center',
    fontFamily: 'NunitoSans-Regular',
    fontSize: 20,
    lineHeight: 20.65,
    fontWeight: '400',
    position: 'relative',
    alignSelf: 'stretch',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botaoCadastrar: {
    flex: 0,
    width: 342.16,
    height: 94.56,
    position: 'static',
  },
  formatoBotao2: {
    backgroundColor: '#fdfdfd',
    borderRadius: 25,
    borderStyle: 'solid',
    borderColor: '#9c2222',
    borderWidth: 1,
    width: '72.11%',
    height: '36.19%',
    position: 'absolute',
    right: '14.37%',
    left: '13.52%',
    bottom: '4.18%',
    top: '59.64%',
  },
  cadastrarTexto: {
    color: '#9c2222',
    textAlign: 'center',
    fontFamily: 'Nunito-Bold',
    fontSize: 20,
    lineHeight: 30.57,
    letterSpacing: 0.68,
    fontWeight: '700',
    textTransform: 'uppercase',
    textDecorationLine: 'underline',
    position: 'absolute',
    right: '0.12%',
    left: '0.12%',
    width: '99.76%',
    bottom: '0%',
    top: '55%',
    height: '45%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
