import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  logupForm: {
    alignItems: "center",
    justifyContent: "flex-start",
    height: 813,
    position: "relative",
    overflow: "hidden",
    aspectRatio: 393 / 813,
  },

  navbar: {
    backgroundColor: "#9c2222",
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    alignSelf: "stretch",
    flexShrink: 0,
    position: "relative",
    overflow: "hidden",
  },

  backbutton: {
    flexShrink: 0,
    width: 44,
    height: 44,
    position: "relative",
    overflow: "visible",
  },

  logo: {
    flexShrink: 0,
    width: 179.47,
    height: 44,
    position: "relative",
    overflow: "visible",
    aspectRatio: 179.47 / 44,
  },

  helpbutton: {
    flexShrink: 0,
    width: 40,
    height: 40,
    position: "relative",
    overflow: "visible",
  },

  conteudo: {
    backgroundColor: "#ffffff",
    paddingVertical: 0,
    paddingHorizontal: 21,
    flexDirection: "column",
    gap: 2,
    alignItems: "center",
    justifyContent: "flex-start",
    alignSelf: "stretch",
    flexShrink: 0,
    height: 739,
    position: "relative",
    overflow: "hidden",
    aspectRatio: 393 / 739,
  },

  tituloconteudo: {
    flexDirection: "column",
    gap: 10,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    flexShrink: 0,
    position: "relative",
  },

  subtitulotexto: {
    color: "#af221f",
    textAlign: "center",
    fontFamily: "NunitoBold",
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: 0.68,
    fontWeight: "700",
    textTransform: "uppercase",
    position: "relative",
    alignSelf: "stretch",
    height: 97,
    textAlignVertical: "center",
  },

  formulariocadastrar: {
    flexDirection: "column",
    gap: 33,
    alignItems: "center",
    justifyContent: "flex-start",
    alignSelf: "stretch",
    flexShrink: 0,
    position: "relative",
  },

  campoimagem: {
    flexDirection: "column",
    gap: 33,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 351,
    position: "relative",
    aspectRatio: 351 / 147,
  },

  imagemtexto: {
    color: "#000000",
    textAlign: "center",
    fontFamily: "NunitoSansRegular",
    fontSize: 20,
    lineHeight: 21,
    fontWeight: "400",
    position: "relative",
    width: 152.52,
  },

  buttonsave: {
    flexShrink: 0,
    width: 56.78,
    height: 44,
    position: "relative",
    overflow: "visible",
  },

  nometexto: {
    color: "#b3b3b3",
    textAlign: "center",
    fontFamily: "InterRegular",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "400",
    position: "relative",
    width: 351,
    height: 16,
  },

  camponome: {
    flexDirection: "column",
    gap: 25,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    width: 351,
    height: 97,
    position: "relative",
    aspectRatio: 351 / 97,
  },

  nometexto2: {
    color: "#000000",
    textAlign: "center",
    fontFamily: "NunitoSansRegular",
    fontSize: 20,
    lineHeight: 21,
    fontWeight: "400",
    position: "relative",
    width: 118.19,
  },

  nomeinput: {
    backgroundColor: "#ffffff",
    borderRadius: 9999,
    borderStyle: "solid",
    borderColor: "#d9d9d9",
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 328,
    height: 51,
    position: "relative",
    overflow: "hidden",
  },

  nometexto3: {
    color: "#b3b3b3",
    textAlign: "center",
    fontFamily: "InterRegular",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "400",
    position: "relative",
    flex: 1,
  },

  cancelarbotao: {
    flexShrink: 0,
    width: 16,
    height: 16,
    position: "relative",
    overflow: "visible",
  },

  campoemail: {
    flexDirection: "column",
    gap: 25,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 351,
    height: 97,
    position: "relative",
    aspectRatio: 351 / 97,
  },

  emailtexto: {
    color: "#000000",
    textAlign: "center",
    fontFamily: "NunitoSansRegular",
    fontSize: 20,
    lineHeight: 21,
    fontWeight: "400",
    position: "relative",
    width: 118.19,
  },

  emailinput: {
    backgroundColor: "#ffffff",
    borderRadius: 9999,
    borderStyle: "solid",
    borderColor: "#d9d9d9",
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 328,
    height: 51,
    position: "relative",
    overflow: "hidden",
  },

  emailtexto2: {
    color: "#b3b3b3",
    textAlign: "center",
    fontFamily: "InterRegular",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "400",
    position: "relative",
    flex: 1,
  },

  cancelarbotao2: {
    flexShrink: 0,
    width: 16,
    height: 16,
    position: "relative",
    overflow: "visible",
  },

  camposenha: {
    flexDirection: "column",
    gap: 24,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 351,
    height: 96,
    position: "relative",
    aspectRatio: 351 / 96,
  },

  senhatexto: {
    color: "#0c0c0c",
    textAlign: "center",
    fontFamily: "NunitoSansRegular",
    fontSize: 20,
    lineHeight: 21,
    fontWeight: "400",
    position: "relative",
    width: 118.19,
  },

  senhatextospan: { color: "#0c0c0c" },
  senhatextospan2: { color: "#243141" },

  senhainput: {
    backgroundColor: "#ffffff",
    borderRadius: 9999,
    borderStyle: "solid",
    borderColor: "#d9d9d9",
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 328,
    height: 51,
    position: "relative",
    overflow: "hidden",
  },

  senhatexto2: {
    color: "#b3b3b3",
    textAlign: "center",
    fontFamily: "InterRegular",
    fontSize: 16,
    lineHeight: 16,
    fontWeight: "400",
    position: "relative",
    flex: 1,
  },

  cancelarbotao3: {
    flexShrink: 0,
    width: 16,
    height: 16,
    position: "relative",
    overflow: "visible",
  },

  campoconfirmar: {
    flexDirection: "column",
    gap: 22,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 351,
    height: 94,
    position: "relative",
    aspectRatio: 351 / 94,
  },

  senhatexto3: {
    color: "#0c0c0c",
    textAlign: "center",
    fontFamily: "NunitoSansRegular",
    fontSize: 20,
    lineHeight: 21,
    fontWeight: "400",
    position: "relative",
    width: 155,
  },

  senhatexto3span: { color: "#0c0c0c" },
  senhatexto3span2: { color: "#243141" },

  cancelarbotao4: {
    flexShrink: 0,
    width: 16,
    height: 16,
    position: "relative",
    overflow: "visible",
  },

  campocep: {
    flexDirection: "column",
    gap: 22,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    width: 351,
    height: 100,
    position: "relative",
    aspectRatio: 351 / 100,
  },

  senhatexto4: {
    color: "#243141",
    textAlign: "center",
    fontFamily: "NunitoSansRegular",
    fontSize: 20,
    lineHeight: 21,
    fontWeight: "400",
    position: "relative",
    width: 155,
  },

  cancelarbotao5: {
    flexShrink: 0,
    width: 16,
    height: 16,
    position: "relative",
    overflow: "visible",
  },

  botaoacao: {
    flexDirection: "column",
    gap: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    flexShrink: 0,
    position: "relative",
  },

  botaocadastrar: {
    flexShrink: 0,
    width: 250,
    height: 48,
    position: "relative",
    aspectRatio: 250 / 48,
  },

  formatobotao: {
    backgroundColor: "#af221f",
    borderRadius: 126,
    borderStyle: "solid",
    borderColor: "#000000",
    borderWidth: 1,
    width: "100%",
    height: "100%",
    position: "absolute",
    right: 0,
    left: 0,
    bottom: 0,
    top: 0,
  },

  cadastrartexto: {
    color: "#ffffff",
    textAlign: "center",
    fontFamily: "NunitoSansBold",
    fontSize: 24,
    fontWeight: "700",
    position: "absolute",
    alignSelf: "center",
    top: 8,
  },

  adicionais: {
    flexDirection: "column",
    gap: 88,
    alignItems: "center",
    justifyContent: "flex-start",
    alignSelf: "stretch",
    flexShrink: 0,
    position: "relative",
  },

  linkentrar: {
    flexShrink: 0,
    width: 205.48,
    height: 86.59,
    position: "relative",
  },

  linktexto: {
    color: "#af221f",
    textAlign: "center",
    fontFamily: "NunitoBold",
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: 0.68,
    fontWeight: "700",
    textTransform: "uppercase",
    textDecorationLine: "underline",
    position: "absolute",
    left: "50%",
    top: "50%",
    width: 350,
    height: 97,
    transform: [{ translateX: -175 }, { translateY: -48.5 }],
    textAlignVertical: "center",
  },

  oauth2: {
    paddingHorizontal: 1,
    flexDirection: "row",
    gap: 60,
    alignItems: "flex-start",
    justifyContent: "center",
    flexShrink: 0,
    position: "relative",
  },

  botaomicrosoft: {
    flexShrink: 0,
    width: 75.23,
    height: 11.84,
    position: "relative",
  },

  microsofticone: {
    width: "100%",
    height: 75.23,
    position: "absolute",
    right: 0,
    left: 0,
    top: 0,
    resizeMode: "cover",
    aspectRatio: 1,
  },

  botaogoogle: {
    flexShrink: 0,
    width: 70.74,
    height: 111.33,
    position: "relative",
  },

  googleicone: {
    width: "100%",
    height: 70.74,
    position: "absolute",
    right: 0,
    left: 0,
    top: 0,
    resizeMode: "cover",
    aspectRatio: 1,
  },
});

export default styles;